version: '3.8'

services:
  webhook:
    build: .
    ports:
      - "9000:9000"  # Expose port 9000
    restart: always
    environment:
      - PROJECTS_FOLDER=${PROJECTS_FOLDER}  # Path to where the project folders are located
    volumes:
      - ${PROJECTS_FOLDER}:${PROJECTS_FOLDER}           # Mount the projects folder
      - /var/run/docker.sock:/var/run/docker.sock  # Give access to the Docker socket
      - ~/.ssh:/root/.ssh:ro
