version: '3.8'

services:
  webhook:
    build: .
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}  # Expose port 9000
    restart: always
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - PROJECTS_FOLDER=${PROJECTS_FOLDER}  # Path to where the project folders are located
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
    volumes:
      - ${PROJECTS_FOLDER}:${PROJECTS_FOLDER}           # Mount the projects folder
      - /var/run/docker.sock:/var/run/docker.sock  # Give access to the Docker socket
      # - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro        # Mount the private key
      # - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro # Mount the public key
